### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by FongMi** [hujiaweibujidao/wava#1]
可以支援 minSdkVersion = 15 嗎 ??

**Comment by hujiaweibujidao** [comment]
wava的library依赖了yava，而yava项目最低设置的是16，所以这里library改成15是不行的。

你可以试下将yava中的4个重要的类复制到wava的library项目中，然后删除library中对yava的依赖，并将minSdkVersion设置为15试试。

抱歉，当时没考虑到要降到这么低 😞

**Comment by FongMi** [comment]
ok, thanks.
